default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  adapter: postgresql
  encoding: unicode
  database: Recipe_App_development
  pool: 5
  username: postgres
  password: postgres

test:
  adapter: postgresql
  encoding: unicode
  database: Recipe_App_test
  pool: 5
  username: postgres
  password: postgres

production:
  <<: *default
  database: Recipe_App_production
  username: postgres
  password: <%= ENV["RAILS_BLOG_APP_DATABASE_PASSWORD"] %>